from datetime import datetime
from ..events import Finding

def generate_markdown_report(
    findings: list[Finding],
    source_file: str,
    events_count: int,
) -> str:
    """Generate a professional Markdown incident report.

    Args:
        findings: List of detected findings.
        source_file: Path to the analyzed log file.
        events_count: Number of events processed.

    Returns:
        Markdown string ready to write to disk.
    """
    # Aggregate findings by severity (normalized to uppercase)
    severity_counts = {}
    for finding in findings:
        sev = finding.severity.upper()
        severity_counts[sev] = severity_counts.get(sev, 0) + 1

    # Generate report timestamp
    report_time = datetime.now().isoformat(timespec='seconds')

    # Build markdown lines
    lines = []
    lines.append("# Security Log Analysis Report")
    lines.append("")
    lines.append(f"**Generated:** {report_time}")
    lines.append(f"**Log File:** {source_file}")
    lines.append(f"**Total Events Processed:** {events_count}")
    lines.append("")

    lines.append("## Executive Summary")
    lines.append("")
    lines.append(f"Analyzed {events_count} events and detected {len(findings)} security finding(s).")
    lines.append("")

    if findings:
        lines.append("| Severity | Count |")
        lines.append("|----------|-------|")
        for severity in ["CRITICAL", "HIGH", "MEDIUM", "LOW"]:
            count = severity_counts.get(severity, 0)
            if count > 0:
                lines.append(f"| {severity} | {count} |")
        lines.append("")

    # Brief findings table
    if findings:
        lines.append("## Findings Summary")
        lines.append("")
        lines.append("| # | Detection | Severity | Time | Entities |")
        lines.append("|---|-----------|----------|------|----------|")

        for idx, finding in enumerate(findings, 1):
            entities_str = ", ".join(f"{k}: {v}" for k, v in finding.entities.items())
            time_str = finding.timestamp.strftime("%Y-%m-%d %H:%M:%S")
            lines.append(f"| {idx} | {finding.detection_name} | {finding.severity.upper()} | {time_str} | {entities_str} |")

        lines.append("")

    # Detailed findings sections
    if findings:
        lines.append("## Detailed Findings")
        lines.append("")

        for idx, finding in enumerate(findings, 1):
            lines.append(f"### {idx}. {finding.detection_name} [{finding.severity.upper()}]")
            lines.append("")

            if finding.attack_id:
                lines.append(f"**ATT&CK Technique:** {finding.attack_id}")
            else:
                lines.append("**ATT&CK Technique:** N/A")
            lines.append("")

            time_str = finding.timestamp.strftime("%Y-%m-%d %H:%M:%S")
            lines.append(f"**Time:** {time_str}")
            lines.append("")

            if finding.entities:
                lines.append("**Entities:**")
                for key, value in finding.entities.items():
                    lines.append(f"- {key}: {value}")
                lines.append("")

            lines.append("**Description:**")
            lines.append("")
            lines.append(finding.description)
            lines.append("")

            if finding.evidence:
                lines.append("**Evidence (supporting log lines):**")
                lines.append("")
                for ev in finding.evidence:
                    lines.append(f"- {ev}")
                lines.append("")

            lines.append("**False Positive Notes:**")
            lines.append("")
            if finding.false_positive_notes:
                lines.append(finding.false_positive_notes)
            else:
                lines.append("None")
            lines.append("")

            lines.append("---")
            lines.append("")

    # Analyst notes placeholder
    lines.append("## Analyst Notes")
    lines.append("")
    lines.append("*Add your analysis, context, and remediation steps below.*")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("Generated by loghound")

    return "\n".join(lines)
